### ISSUE TITLE
Numpy incompatibility

### ISSUE THREAD

**Issue by RemyBorius** [MaxHalford/vose#5]
Hi,

I just installed the lib of @MaxHalford sorobn, and first thing that happens when I import it is this error that say there is an incompatibility with numpy :
```
File "/home/remy/anaconda3/envs/parallelProgramming/lib/python3.10/site-packages/sorobn/bayes_net.py", line 10, in <module>
    import vose
  File "/home/remy/anaconda3/envs/parallelProgramming/lib/python3.10/site-packages/vose/__init__.py", line 1, in <module>
    from .sampler import Sampler
  File "vose/sampler.pyx", line 1, in init vose.sampler
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 232 from C header, got 216 from PyObject
```

Could you fix it, or specify the required version of numpy ?

I'm using last numpy version from anaconda : 1.21.5

**Comment by RemyBorius** [comment]
Actually upgrading to 1.22.0 was enough for it to work (it seems for now).

But maybe other people how use the default provided numpy version of conda will experience the same issue

**Comment by MaxHalford** [comment]
Hey Remy, thanks for opening an issue. I've seen this error pop up in different contexts, and I'm not sure what to attribute it to. I'm going to set `numpy>=1.22` and call it a day. Thanks!
