### ISSUE TITLE
Publishing to PyPI

### ISSUE THREAD

**Issue by pmbaumgartner** [MaxHalford/vose#6]
Hey @MaxHalford  -

Thank you for this awesome implementation! I wonder if you'd reconsider publishing the package to PyPI? I'm using it as a dependency in a small bootstrapping package I wrote (https://github.com/pmbaumgartner/boots), however, I can't upload that package to PyPI with a dependency that's pulled from GitHub.

**Comment by MaxHalford** [comment]
Hey there @pmbaumgartner. Sure, I could do that! The thing is my computer is broken at the moment, so it'll have to wait a week or so. But I'll add it to my to do and let you know :)

**Comment by MaxHalford** [comment]
Cool library by the way, nice API.

**Comment by MaxHalford** [comment]
[Here you go](https://pypi.org/project/vose/0.0.1/) @pmbaumgartner :)
